"""Widths of the standard PDF fonts (Times, Helvetica) for the WinAnsi encoding, used by
src/io/pdf.js to measure and place text without embedding any font.

Source: the Adobe Core 14 AFM files bundled with matplotlib (mpl-data/fonts/pdfcorefonts).
Run: python3 web/tools/build_pdf_fonts.py   -> web/src/data/pdf-fonts.js
"""
import json
import os

import matplotlib
from fontTools import agl

AFM = os.path.join(os.path.dirname(matplotlib.__file__), 'mpl-data', 'fonts', 'pdfcorefonts')
FONTS = ['Times-Roman', 'Times-Italic', 'Times-Bold', 'Helvetica', 'Helvetica-Bold']


def widths(name):
    by_glyph = {}
    with open(os.path.join(AFM, name + '.afm'), encoding='latin-1') as fh:
        for line in fh:
            if not line.startswith('C '):
                continue
            parts = dict(p.strip().split(' ', 1) for p in line.strip().split(';') if p.strip())
            by_glyph[parts['N']] = int(float(parts['WX']))
    out = []
    for code in range(32, 256):
        try:
            ch = bytes([code]).decode('cp1252')
        except UnicodeDecodeError:
            out.append(by_glyph.get('space', 250))
            continue
        glyph = agl.UV2AGL.get(ord(ch), 'space')
        if code == 0xA0:
            glyph = 'space'
        if code == 0xAD:
            glyph = 'hyphen'
        out.append(by_glyph.get(glyph, by_glyph.get('space', 250)))
    return out


here = os.path.dirname(os.path.abspath(__file__))
data = {name: widths(name) for name in FONTS}
with open(os.path.join(here, '..', 'src', 'data', 'pdf-fonts.js'), 'w') as fh:
    fh.write('// Generated by tools/build_pdf_fonts.py from the Adobe Core 14 AFM files. Do not edit.\n')
    fh.write('// Advance widths (1/1000 em) of WinAnsi codes 32-255 for the standard PDF fonts.\n')
    fh.write('export default ' + json.dumps(data, separators=(',', ':')) + ';\n')
print('ok', {k: len(v) for k, v in data.items()})
