// Precomputes the example shown when the page opens (so the first view is a real result).
// It is exactly what «Gerar» produces with the default configuration.
//   node tools/make_examples.mjs
import { writeFileSync } from 'node:fs';
import { createGA } from '../src/ga/ga.js';
import { createRng } from '../src/core/rng.js';
import { defaultConfig, buildFitness } from '../src/ui/config.js';

const here = new URL('.', import.meta.url).pathname;
const cfg = defaultConfig();
const seed = cfg.ga.seed;
const built = buildFitness(cfg);
const ga = createGA({
  fitness: built.fit, rng: createRng(seed), length: built.fit.length, env: built.env,
  generations: cfg.ga.generations, popSize: cfg.ga.popSize, mutationRate: cfg.ga.mutation,
  strategy: 'tournament', operators: 'musical',
});
ga.step(cfg.ga.generations);
const examples = [{
  title: `Exemplo · campo de atratores (arco de frase), Sol maior, semente ${seed}`,
  seed,
  genes: ga.best.decoded,
  history: ga.history.map((h) => ({ ...h, best: +h.best.toFixed(3), mean: +h.mean.toFixed(3), diversity: +h.diversity.toFixed(4) })),
}];
writeFileSync(`${here}../src/data/examples.js`, `// generated by tools/make_examples.mjs\nexport const EXAMPLES = ${JSON.stringify(examples)};\n`);
console.log('fitness', ga.best.fitness.toFixed(2));
