// Precomputes the example shown when the page opens (so the first view is a real result).
//   node tools/make_examples.mjs
import { writeFileSync } from 'node:fs';
import { createAttractorFitness, DEFAULT_WEIGHTS } from '../src/fitness/attractor.js';
import { resolvePreset } from '../src/fitness/presets.js';
import { createGA } from '../src/ga/ga.js';
import { createRng } from '../src/core/rng.js';

const here = new URL('.', import.meta.url).pathname;
const seed = 7;
const fit = createAttractorFitness({
  bars: 8, tonic: 7, mode: 'major', waves: resolvePreset('arch', 7), basinShape: 'gaussian',
  form: "AA'BA'", phraseBars: 2, weights: DEFAULT_WEIGHTS, seed,
});
const ga = createGA({ fitness: fit, rng: createRng(seed), length: fit.length, env: fit.env, generations: 600, popSize: 80, mutationRate: 0.9, strategy: 'tournament', operators: 'musical' });
ga.step(600);
const examples = [{
  title: 'Exemplo · campo de atratores (arco de frase), Sol maior, semente 7',
  seed,
  genes: ga.best.decoded,
  history: ga.history.map((h) => ({ ...h, best: +h.best.toFixed(3), mean: +h.mean.toFixed(3), diversity: +h.diversity.toFixed(4) })),
}];
writeFileSync(`${here}../src/data/examples.js`, `// generated by tools/make_examples.mjs\nexport const EXAMPLES = ${JSON.stringify(examples)};\n`);
console.log('fitness', ga.best.fitness.toFixed(2));
