// Trains the evaluation critic and writes web/data/critic.json.
//   node tools/train_critic.mjs
// Positives: the reference corpus (data/corpus.json). Negatives: null models (nullmodels.js).
// The n-gram expectation model is cross-fitted (2 folds) so corpus melodies are never scored
// by a model that has seen them.

import { readFileSync, writeFileSync } from 'node:fs';
import { createRng } from '../src/core/rng.js';
import { melodyFeatures } from '../src/eval/metrics.js';
import { trainModel, makeModel } from '../src/eval/ngram.js';
import { nullMelody, NULL_TYPES } from '../src/eval/nullmodels.js';
import { CRITIC_FEATURES, standardize, trainLogistic, predict, auc } from '../src/eval/critic.js';

const here = new URL('.', import.meta.url).pathname;
const corpus = JSON.parse(readFileSync(`${here}../data/corpus.json`, 'utf8')).melodies;
const rng = createRng(12345);

// ---- n-gram model: full (for new melodies) and 2-fold cross-fitted (for the corpus itself)
const folds = corpus.map((_, i) => i % 2);
const fullModel = makeModel(trainModel(corpus.map((m) => m.events)));
const foldModels = [0, 1].map((f) => makeModel(trainModel(corpus.filter((_, i) => folds[i] !== f).map((m) => m.events))));

const pos = corpus.map((m, i) => melodyFeatures(m.events, { barLen: m.barLen, pickup: m.pickup }, foldModels[folds[i]]));
const negEvents = [];
const negTypes = [];
const perType = Math.round(corpus.length / NULL_TYPES.length);
for (const t of NULL_TYPES) {
  for (let k = 0; k < perType; k++) {
    negEvents.push(nullMelody(t, rng, corpus));
    negTypes.push(t);
  }
}
const neg = negEvents.map((e) => melodyFeatures(e, { barLen: 16, pickup: 0 }, fullModel));

// ---- standardisation on the corpus
const mean = CRITIC_FEATURES.map((f) => pos.reduce((a, r) => a + r[f], 0) / pos.length);
const sd = CRITIC_FEATURES.map((f, j) => Math.sqrt(pos.reduce((a, r) => a + (r[f] - mean[j]) ** 2, 0) / pos.length) || 1);
const stats = { features: CRITIC_FEATURES, mean, sd };
const X = standardize(pos.concat(neg), stats);
const y = pos.map(() => 1).concat(neg.map(() => 0));

// ---- 5-fold cross-validation
const idx = rng.shuffle([...X.keys()]);
const cvScores = new Array(X.length);
for (let f = 0; f < 5; f++) {
  const test = new Set(idx.filter((_, k) => k % 5 === f));
  const trX = [];
  const trY = [];
  X.forEach((x, i) => {
    if (!test.has(i)) {
      trX.push(x);
      trY.push(y[i]);
    }
  });
  const m = trainLogistic(trX, trY);
  for (const i of test) cvScores[i] = predict(m, X[i]);
}
const cvAuc = auc(cvScores, y);
const cvAcc = cvScores.filter((s, i) => (s >= 0.5) === (y[i] === 1)).length / y.length;
const perTypeAcc = {};
for (const t of NULL_TYPES) {
  const ids = negTypes.map((nt, k) => (nt === t ? pos.length + k : -1)).filter((k) => k >= 0);
  perTypeAcc[t] = ids.filter((i) => cvScores[i] < 0.5).length / ids.length;
}
perTypeAcc.corpus = pos.map((_, i) => cvScores[i] >= 0.5).filter(Boolean).length / pos.length;

const logistic = trainLogistic(X, y);
const percentiles = CRITIC_FEATURES.map((f) => {
  const v = pos.map((r) => r[f]).sort((a, b) => a - b);
  const q = (p) => v[Math.min(v.length - 1, Math.floor(p * v.length))];
  return [q(0.1), q(0.5), q(0.9)];
});

const out = {
  description: 'Logistic critic: real melodies vs null models. Features standardised on the corpus.',
  features: CRITIC_FEATURES,
  mean,
  sd,
  logistic,
  percentiles,
  cv: { auc: cvAuc, accuracy: cvAcc, perClassAccuracy: perTypeAcc },
  ngram: fullModel.tables,
  corpusSize: corpus.length,
};
writeFileSync(`${here}../data/critic.json`, JSON.stringify(out));
// ES-module copies of the data, so the page works without fetch() (file:// or single-file build)
writeFileSync(`${here}../src/data/critic-data.js`, `// generated by tools/train_critic.mjs\nexport default ${JSON.stringify(out)};\n`);
const slim = corpus.map(({ source, title, barLen, pickup, tonic, mode, events }) => ({ source, title, barLen, pickup, tonic, mode, events }));
writeFileSync(`${here}../src/data/corpus-data.js`, `// generated by tools/train_critic.mjs from data/corpus.json\nexport default ${JSON.stringify(slim)};\n`);
console.log('CV AUC', cvAuc.toFixed(3), 'accuracy', cvAcc.toFixed(3));
console.log('per class accuracy', Object.fromEntries(Object.entries(perTypeAcc).map(([k, v]) => [k, +v.toFixed(3)])));
const ranked = CRITIC_FEATURES.map((f, j) => [f, logistic.w[j]]).sort((a, b) => Math.abs(b[1]) - Math.abs(a[1]));
console.log('largest weights', ranked.slice(0, 10).map(([f, w]) => `${f}:${w.toFixed(2)}`).join(' '));
console.log('corpus medians', Object.fromEntries(CRITIC_FEATURES.map((f, j) => [f, +percentiles[j][1].toFixed(3)])));
